### ISSUE TITLE
Belgian xbrl with pfs: how to get the pfs info with gepsio: documentation

### ISSUE THREAD

**Issue by ghisbo** [JeffFerguson/gepsio#41]
Hello, i try to implement gepsio to extract the pfs info from xbrl but i see no way to do it.
I can get context and units but that's it.
I include  a anonimised 
[Test.zip](https://github.com/JeffFerguson/gepsio/files/6097988/Test.zip)

test.xbrl  file

Thanks in advance

**Comment by Wimsteppe** [comment]
Gepsio cannot handle the denominations of our Belgian system. They are represented as http links, but are leading nowhere. Gepsio looks on the http location for the taxonomy, but cannot find anything. We encountered the same issue with the corporate tax returns. You'd have to download the taxonomy locally or publish them online for Gepsio to be able to work with it.

To work around this, you could change the logic in the XbrlSchema so it loads properly from a file location. 

Created a quick hardcoded entry to illustrate this with working example on a BE .XBRL. Ideally we can include this in the core Gepsio as a configuration option. Also, please note that the console app is not a "clean" example, I made some internal code public instead of properly investigating the examples and used some hardcoded entries which really should not be there in the interest of time.

[gepsio-master.zip](https://github.com/JeffFerguson/gepsio/files/6144596/gepsio-master.zip)

**Comment by ghisbo** [comment]
OK, made it work
Thanks
